/* Generated by SharpKit 5 v5.4.4 */

if (typeof(mvcLocalize) == "undefined")
    var mvcLocalize = {};
if (typeof(mvcLocalize.server) == "undefined")
    mvcLocalize.server = {};
mvcLocalize.server.someCustomClass = function (){
};
mvcLocalize.server.someCustomClass.inst = new mvcLocalize.server.someCustomClass();
mvcLocalize.server.someCustomClass.prototype.x = function (){
    return "i am x";
};
mvcLocalize.server.someCustomClass.prototype.y = function (){
    return "i am y";
};

